// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SolarTracker.Api.Data;

#nullable disable

namespace SolarTracker.Api.Migrations
{
    [DbContext(typeof(SolarTrackerDbContext))]
    [Migration("20260701160814_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SolarTracker.Api.Data.TelemetrySnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AtsStatus")
                        .HasColumnType("integer");

                    b.Property<double>("Azimuth")
                        .HasColumnType("double precision");

                    b.Property<double>("BatteryLevel")
                        .HasColumnType("double precision");

                    b.Property<double>("Current")
                        .HasColumnType("double precision");

                    b.Property<double>("Elevation")
                        .HasColumnType("double precision");

                    b.Property<double>("InverterOutputW")
                        .HasColumnType("double precision");

                    b.Property<double>("LightIntensity")
                        .HasColumnType("double precision");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<double>("Power")
                        .HasColumnType("double precision");

                    b.Property<int>("PowerSource")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<double>("TargetAzimuth")
                        .HasColumnType("double precision");

                    b.Property<double>("TargetElevation")
                        .HasColumnType("double precision");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Voltage")
                        .HasColumnType("double precision");

                    b.Property<double>("WindDirection")
                        .HasColumnType("double precision");

                    b.Property<double>("WindSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Telemetry");
                });
#pragma warning restore 612, 618
        }
    }
}
